%define INSTANCEHOME instance
instancehome $INSTANCEHOME

%define CLIENTHOME instance
clienthome $CLIENTHOME

debug-mode off
security-policy-implementation C
verbose-security off

default-zpublisher-encoding utf-8
<zodb_db main>
    <filestorage>
        path $CLIENTHOME/var/Data.fs
        blob-dir $CLIENTHOME/var/blobs
    </filestorage>
    mount-point /
</zodb_db>
